server:
  port: 8083


spring:
 # application:
  #  name: SALES-ORDER-SERVICE
  datasource:
    url: jdbc:h2:mem:salesorderdb
  jpa:
    defer-datasource-initialization: true


#eureka:
 # client:
  #  register-with-eureka: true
   # fetch-registry: true
    #service-url:
     # defaultZone: http://localhost:8761/eureka/
    #instance:
     # hostname: localhost